# Generated by Django 5.0.3 on 2024-03-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "registration",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
